### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [prabhatkc/mpi4py_patches#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by prabhatkc** [comment]
@suprafun , if it is to study or for academic research purposes, feel free to download and edit or modify or use parts of this implementation at it pleases you. However, if it is for commercial purpose, I will get back to you in few days with explicit license text.

**Comment by prabhatkc** [comment]
@suprafun , I have added license text in the readme file.

**Comment by suprafun** [comment]
Sorry for my late reply. Thank you so very much for taking the time to provide a explicit license.
